name: nf-test CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

env:
  NFT_DIFF: "pdiff"
  NFT_DIFF_ARGS: "--line-numbers --width 120 --expand-tabs=2"
  NFT_VER: "0.9.2"
  NFT_WORKDIR: "${{ github.workspace }}/nf-test-work"
  NXF_ANSI_LOG: false
  NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/.singularity
  NXF_SINGULARITY_LIBRARYDIR: ${{ github.workspace }}/.singularity

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Test ${{ matrix.filter }} | ${{ matrix.profile }} | ${{ matrix.NXF_VER }} | ${{ matrix.shard }}/5"
    strategy:
      fail-fast: false
      matrix:
        NXF_VER:
          - "24.10.2"
          - "latest-everything"
        filter: ["pipeline"]
        # filter: ["process", "workflow", "function", "pipeline"]
        profile: ["conda", "docker", "singularity"]
        shard: [1] 
        # shard: [1, 2, 3, 4, 5]

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5
        with:
          python-version: "3.11"

      - uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Set up nf-test
        uses: nf-core/setup-nf-test@v1
        with:
          version: ${{ env.NFT_VER }}

      - name: Set up apptainer
        if: matrix.profile == 'singularity'
        uses: eWaterCycle/setup-apptainer@main

      - name: Set up Singularity
        if: matrix.profile == 'singularity'
        run: |
          mkdir -p $NXF_SINGULARITY_CACHEDIR
          mkdir -p $NXF_SINGULARITY_LIBRARYDIR

      - name: Install pdiff
        run: python -m pip install --upgrade pip pdiff cryptography

      - name: Set up miniconda
        if: matrix.profile == 'conda'
        uses: conda-incubator/setup-miniconda@835234971496cad1653abb28a638a281cf32541f # v3
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          conda-solver: libmamba
          channels: conda-forge,bioconda

      - name: Set up Conda
        if: matrix.profile == 'conda'
        run: |
          echo $(realpath $CONDA)/condabin >> $GITHUB_PATH
          echo $(realpath python) >> $GITHUB_PATH

      #- name: Disk space cleanup
      #  uses: jlumbroso/free-disk-space@v1.3.1

      - name: Start summary
        id: print-test
        run: |
          echo "## nf-test tests summary :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "This \`${{ matrix.filter }}\` ${{ matrix.shard }}/5 shard was run on \`${{ matrix.profile }}\` | \`NXF_VER=${{ matrix.NXF_VER }}\`, and contains the following test(s):" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          nf-test test \
            --ci \
            --dryRun \
            --junitxml="TEST-${{ matrix.filter }}_${{ matrix.profile }}_${{ matrix.shard }}.xml" \
            --shard ${{ matrix.shard }}/1 \
            --follow-dependencies \
            --profile "+${{ matrix.profile }}" \
            --filter ${{ matrix.filter }} \
            | grep PASSED | cut -d "'" -f 2 | sed 's/^/- /' | sort -u >> $GITHUB_STEP_SUMMARY

      - name: "Run tests | ${{ matrix.filter }}_${{ matrix.profile }} | ${{ matrix.shard }}/1"
        run: |
          nf-test test \
              --ci \
              --debug \
              --verbose \
              --junitxml="TEST-${{ matrix.filter }}_${{ matrix.profile }}_${{ matrix.shard }}.xml" \
              --shard ${{ matrix.shard }}/1 \
              --follow-dependencies \
              --profile "+${{ matrix.profile }}" \
              --filter ${{ matrix.filter }}

      - name: Print success in summary
        if: success()
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All test(s) successfull :tada:" >> $GITHUB_STEP_SUMMARY

      - name: Print failure in summary
        if: failure()
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Some test(s) failed :cold_sweat:" >> $GITHUB_STEP_SUMMARY

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: "TEST-*.xml"

      - name: Upload test results
        if: always()  # run even if tests fail
        uses: actions/upload-artifact@v6
        with:
          name: nf-test-results-${{ matrix.filter }}-${{ matrix.profile }}-${{ matrix.NXF_VER }}-${{ matrix.shard }}
          path: |
            TEST-*.xml
            ${{ env.NFT_WORKDIR }}/**/output/**
          retention-days: 4

      - name: Clean up
        if: success() || failure()
        run: |
          sudo rm -rf /home/ubuntu/tests/
